import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase.js'
import { buildSwimmingPlanGuardrails, getRecommendedSwimmingWeeks } from '../lib/swimmingPlanGenerator.js'

const DRAFT_KEY='swimming_onboarding_draft_v2'
const DAYS=['Mo','Di','Mi','Do','Fr','Sa','So']
const DEFAULT_DAYS={2:['Di','Sa'],3:['Di','Do','So'],4:['Mo','Mi','Fr','So']}
const DISTANCES=[500,1000,1500,2000,3000]
const CONTINUOUS=[25,50,100,200,400,800,1500]
const SESSION=[250,500,750,1000,1500,2000,2500,3000]
const todayIso=()=>new Date().toISOString().split('T')[0]
const weeksBetween=(a,b)=>{if(!a||!b)return null;const s=new Date(`${a}T12:00:00`),e=new Date(`${b}T12:00:00`);const d=Math.floor((e-s)/86400000);return d<7?0:Math.floor(d/7)}
const card=s=>({width:'100%',padding:'13px 14px',borderRadius:15,border:`2px solid ${s?'#6BA7A0':'#E7E0DA'}`,background:s?'#EFF8F7':'#fff',color:s?'#467F79':'#76675F',fontFamily:'sans-serif',fontWeight:800,fontSize:11.5,cursor:'pointer',textAlign:'left'})
const chip=s=>({padding:'10px 11px',borderRadius:11,border:`1.5px solid ${s?'#6BA7A0':'#E8DFD8'}`,background:s?'#EFF8F7':'#fff',color:s?'#467F79':'#806F65',fontFamily:'sans-serif',fontWeight:800,fontSize:10.5,cursor:'pointer'})
const label={fontSize:10,fontWeight:900,color:'#8F7B70',letterSpacing:.7,textTransform:'uppercase',fontFamily:'sans-serif',marginBottom:7}
const input={width:'100%',padding:'12px 13px',borderRadius:12,border:'1.5px solid #E8DDD6',background:'#FFFDFC',fontSize:14,boxSizing:'border-box',outline:'none'}
const panel={background:'#fff',border:'1px solid #E9E1DC',borderRadius:20,padding:18,boxShadow:'0 8px 28px rgba(68,53,44,.06)'}
const small={fontFamily:'sans-serif',fontSize:10.5,lineHeight:1.45,color:'#9A877C'}

export default function SwimmingOnboarding({onPlanGenerated}){
  const [step,setStep]=useState(1),[loading,setLoading]=useState(false),[error,setError]=useState(null),[weeksManual,setWeeksManual]=useState(false)
  const [form,setForm]=useState(()=>{
    const initial={name:'',goalType:'',stroke:'freestyle',mixedPriority:'freestyle',targetDistanceM:'',customDistanceM:'',continuousGoal:'yes',eventDate:'',venue:'pool',openWaterAccess:'no',
      currentFrequency:'0',currentSessionM:500,currentContinuousM:50,techniqueLevel:'okay',techniqueFocus:[],poolLength:'25m',equipment:[],
      unitsPerWeek:3,preferredDays:DEFAULT_DAYS[3],startDate:todayIso(),weeksUntilGoal:10}
    if(typeof window==='undefined')return initial
    try{const saved=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'null');return saved?.form?{...initial,...saved.form}:initial}catch{return initial}
  })
  useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'null');if(saved?.step)setStep(saved.step);if(saved?.weeksManual)setWeeksManual(true)}catch{}},[])
  useEffect(()=>{try{sessionStorage.setItem(DRAFT_KEY,JSON.stringify({step,form,weeksManual}))}catch{}},[step,form,weeksManual])
  useEffect(()=>{let active=true;(async()=>{try{const {data:a}=await supabase.auth.getUser();if(!a?.user?.id)return;const {data}=await supabase.from('profiles').select('name').eq('id',a.user.id).maybeSingle();if(active)setForm(c=>({...c,name:data?.name||a.user.user_metadata?.name||c.name}))}catch{}})();return()=>{active=false}},[])
  const eventWeeks=useMemo(()=>weeksBetween(form.startDate,form.eventDate),[form.startDate,form.eventDate])
  const effective={...form,targetDistanceM:Number(form.customDistanceM||form.targetDistanceM||0)}
  const recommendation=useMemo(()=>getRecommendedSwimmingWeeks(effective),[form.goalType,form.targetDistanceM,form.customDistanceM,form.currentContinuousM,form.currentSessionM,form.unitsPerWeek,form.continuousGoal])
  useEffect(()=>{if(form.goalType==='event'&&eventWeeks>0){setWeeksManual(false);setForm(c=>({...c,weeksUntilGoal:eventWeeks}));return}if(!weeksManual)setForm(c=>({...c,weeksUntilGoal:recommendation}))},[form.goalType,eventWeeks,recommendation,weeksManual])
  const set=(k,v)=>setForm(c=>({...c,[k]:v}))
  const toggle=(k,v)=>setForm(c=>({...c,[k]:c[k].includes(v)?c[k].filter(x=>x!==v):[...c[k],v]}))
  const selectUnits=n=>setForm(c=>({...c,unitsPerWeek:n,preferredDays:DEFAULT_DAYS[n]}))
  const toggleDay=d=>setForm(c=>{const has=c.preferredDays.includes(d);if(has)return{...c,preferredDays:c.preferredDays.filter(x=>x!==d)};if(c.preferredDays.length>=c.unitsPerWeek)return c;return{...c,preferredDays:[...c.preferredDays,d]}})
  const needsTarget=['distance','event'].includes(form.goalType)
  const can1=Boolean(form.goalType&&form.stroke)&&(!needsTarget||Number(effective.targetDistanceM)>0)&&(form.goalType!=='event'||(form.eventDate&&eventWeeks>0))
  const can2=Boolean(form.currentFrequency&&form.currentSessionM&&form.currentContinuousM&&form.techniqueLevel&&form.poolLength)
  const can3=form.preferredDays.length===form.unitsPerWeek&&form.weeksUntilGoal>=6
  const focusOptions=form.stroke==='breaststroke'?['Atmung','Armzug','Beinschlag','Timing/Koordination','Gleiten','Wenden']:['Atmung','Wasserlage','Armzug','Beinschlag','Rhythmus/Koordination','Wenden']
  const generate=async()=>{setLoading(true);setError(null);try{const {dayDurations:_legacyDayDurations,...cleanEffective}=effective;const payload={...cleanEffective,sport_type:'swimming',plan_type:'swimming_endurance',guardrails:buildSwimmingPlanGuardrails(cleanEffective)};const r=await fetch('/api/generate-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok||data?.error)throw new Error(data?.error||`HTTP ${r.status}`);if(!data?.plan?.phases?.length)throw new Error('Der Trainingsplan ist unvollständig.');sessionStorage.removeItem(DRAFT_KEY);onPlanGenerated(data.plan)}catch(e){setError(`Dein Plan konnte gerade nicht erstellt werden: ${e.message}`)}finally{setLoading(false)}}
  const Goal=({id,icon,title,text})=><button type="button" style={card(form.goalType===id)} onClick={()=>set('goalType',id)}><span style={{fontSize:20,marginRight:9}}>{icon}</span>{title}<div style={{...small,margin:'5px 0 0 30px'}}>{text}</div></button>
  const Chips=({values,value,onChange,format=x=>x})=><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{values.map(v=><button type="button" key={v} style={chip(value===v)} onClick={()=>onChange(v)}>{format(v)}</button>)}</div>

  return <div style={{minHeight:'100vh',background:'linear-gradient(160deg,#F2FAFA 0%,#FFF9F3 55%,#F4F2FA 100%)',color:'#44342B'}}>
    <header style={{minHeight:245,position:'relative',overflow:'hidden',display:'flex',alignItems:'flex-end',background:'#567C7C'}}>
      <div style={{position:'absolute',inset:0,backgroundImage:'url("/hero/swimming/03.webp")',backgroundSize:'cover',backgroundPosition:'center'}}/>
      <div style={{position:'absolute',inset:0,background:'linear-gradient(90deg,rgba(20,38,40,.76),rgba(20,38,40,.32) 65%,rgba(20,38,40,.12)),linear-gradient(180deg,transparent,rgba(20,30,32,.62))'}}/>
      <div style={{position:'relative',zIndex:1,width:'100%',maxWidth:720,margin:'0 auto',padding:'32px 20px 24px',boxSizing:'border-box',color:'#fff'}}><div style={{fontFamily:'sans-serif',fontSize:10,fontWeight:900,letterSpacing:1.4}}>DEIN TRAININGSPLAN</div><h1 style={{margin:'7px 0 4px',fontSize:31}}>Schwimmen</h1><div style={{fontFamily:'sans-serif',fontSize:12,lineHeight:1.5,opacity:.92}}>Technik, Ausdauer und längere Strecken – passend zu deinem aktuellen Stand.</div></div>
    </header>
    <main style={{maxWidth:720,margin:'0 auto',padding:'18px 14px 40px'}}>
      <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:7,marginBottom:14}}>{['Ziel','Training','Plan'].map((x,i)=><div key={x} style={{padding:'8px',textAlign:'center',borderRadius:10,background:step===i+1?'#EAF6F5':'rgba(255,255,255,.7)',fontFamily:'sans-serif',fontSize:9.5,fontWeight:900,color:step===i+1?'#4C8B84':'#A08E83'}}>{i+1} · {x}</div>)}</div>
      {step===1&&<div style={panel}><h2 style={{margin:'0 0 14px',fontSize:22}}>Was möchtest du erreichen?</h2><div style={{display:'grid',gap:8}}>
        <Goal id="beginner" icon="🌱" title="Mit Schwimmen anfangen" text="Regelmäßig trainieren, Technik entwickeln und nach und nach länger schwimmen."/><Goal id="distance" icon="🎯" title="Eine Distanz schaffen" text="Gezielt darauf hinarbeiten, eine bestimmte Strecke zu schwimmen."/><Goal id="event" icon="🏁" title="Für ein Schwimm-Event trainieren" text="Vorbereitung auf einen Wettkampf oder ein konkretes Schwimmziel."/><Goal id="fitness" icon="💪" title="Meine Schwimmfitness verbessern" text="Ausdauer, Technik und Leistungsfähigkeit weiterentwickeln."/></div>
        <div style={{marginTop:18}}><div style={label}>Wie möchtest du hauptsächlich schwimmen?</div><Chips values={['freestyle','breaststroke','mixed']} value={form.stroke} onChange={v=>set('stroke',v)} format={v=>({freestyle:'Kraul',breaststroke:'Brust',mixed:'Kraul & Brust'}[v])}/></div>
        {form.stroke==='mixed'&&<div style={{marginTop:14}}><div style={label}>Welche Schwimmart möchtest du stärker entwickeln?</div><Chips values={['freestyle','breaststroke','equal']} value={form.mixedPriority} onChange={v=>set('mixedPriority',v)} format={v=>({freestyle:'Kraul',breaststroke:'Brust',equal:'Beide gleich'}[v])}/></div>}
        {needsTarget&&<div style={{marginTop:18}}><div style={label}>Welche Distanz möchtest du {form.goalType==='event'?'schwimmen?':'schaffen?'}</div><Chips values={[...DISTANCES,'custom']} value={form.customDistanceM!==''?'custom':Number(form.targetDistanceM)} onChange={v=>v==='custom'?setForm(c=>({...c,targetDistanceM:'',customDistanceM:c.customDistanceM||'5000'})):setForm(c=>({...c,targetDistanceM:v,customDistanceM:''}))} format={v=>v==='custom'?'Eigene Distanz':`${v.toLocaleString('de-DE')} m`}/>{form.customDistanceM!==''&&<div style={{marginTop:9}}><input style={input} type="number" min="100" step="25" placeholder="z. B. 5000" value={form.customDistanceM} onChange={e=>set('customDistanceM',e.target.value)}/></div>}{form.goalType==='distance'&&<div style={{marginTop:14}}><div style={label}>Möchtest du diese Distanz am Stück schwimmen können?</div><Chips values={['yes','no']} value={form.continuousGoal} onChange={v=>set('continuousGoal',v)} format={v=>v==='yes'?'Ja, am Stück':'Nein, als Gesamtstrecke'}/></div>}</div>}
        {form.goalType==='event'&&<><div style={{marginTop:15}}><div style={label}>Wann findet dein Event statt?</div><input style={input} type="date" min={form.startDate} value={form.eventDate} onChange={e=>set('eventDate',e.target.value)}/></div><div style={{marginTop:14}}><div style={label}>Wo findet es statt?</div><Chips values={['pool','open_water']} value={form.venue} onChange={v=>set('venue',v)} format={v=>v==='pool'?'Becken':'Freiwasser'}/></div>{form.venue==='open_water'&&<div style={{marginTop:14}}><div style={label}>Kannst du sicher im Freiwasser trainieren?</div><Chips values={['regular','sometimes','no']} value={form.openWaterAccess} onChange={v=>set('openWaterAccess',v)} format={v=>({regular:'Ja, regelmäßig',sometimes:'Gelegentlich',no:'Nein'}[v])}/></div>}</>}
        <button disabled={!can1} onClick={()=>setStep(2)} style={{...card(can1),marginTop:20,textAlign:'center',opacity:can1?1:.45}}>Weiter →</button></div>}
      {step===2&&<div style={panel}><h2 style={{margin:'0 0 15px',fontSize:22}}>Wie schwimmst du aktuell?</h2><div style={label}>Wie oft schwimmst du derzeit?</div><Chips values={['0','1','2','3','4plus']} value={form.currentFrequency} onChange={v=>set('currentFrequency',v)} format={v=>({0:'Gar nicht',1:'1×',2:'2×',3:'3×','4plus':'4× oder häufiger'}[v])}/>
        <div style={{marginTop:16}}><div style={label}>Typische Gesamtstrecke pro Einheit</div><Chips values={SESSION} value={Number(form.currentSessionM)} onChange={v=>set('currentSessionM',v)} format={v=>`${v.toLocaleString('de-DE')} m`}/></div><div style={{marginTop:16}}><div style={label}>Wie weit schaffst du ungefähr ohne längere Pause?</div><Chips values={CONTINUOUS} value={Number(form.currentContinuousM)} onChange={v=>set('currentContinuousM',v)} format={v=>v===1500?'1.500 m+':`${v} m`}/></div>
        <div style={{marginTop:16}}><div style={label}>Wie sicher fühlst du dich technisch?</div><Chips values={['unsure','okay','secure']} value={form.techniqueLevel} onChange={v=>set('techniqueLevel',v)} format={v=>({unsure:'Noch unsicher',okay:'Ganz okay',secure:'Sicher'}[v])}/></div><div style={{marginTop:16}}><div style={label}>Was möchtest du technisch verbessern? <span style={{textTransform:'none',fontWeight:600}}>optional, mehrfach</span></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{focusOptions.map(v=><button type="button" key={v} style={chip(form.techniqueFocus.includes(v))} onClick={()=>toggle('techniqueFocus',v)}>{v}</button>)}</div></div>
        <div style={{marginTop:16}}><div style={label}>In welchem Becken trainierst du normalerweise?</div><Chips values={['25m','50m','both']} value={form.poolLength} onChange={v=>set('poolLength',v)} format={v=>({'25m':'25 m','50m':'50 m',both:'Beides'}[v])}/></div><div style={{marginTop:16}}><div style={label}>Welche Hilfsmittel stehen dir zur Verfügung? <span style={{textTransform:'none',fontWeight:600}}>optional</span></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{['Pullbuoy','Brett','Flossen','Paddles'].map(v=><button type="button" key={v} style={chip(form.equipment.includes(v))} onClick={()=>toggle('equipment',v)}>{v}</button>)}</div><div style={{...small,marginTop:7}}>Der Plan funktioniert auch vollständig ohne Hilfsmittel.</div></div>
        <div style={{display:'flex',gap:8,marginTop:20}}><button onClick={()=>setStep(1)} style={{...card(false),textAlign:'center'}}>← Zurück</button><button disabled={!can2} onClick={()=>setStep(3)} style={{...card(can2),textAlign:'center',opacity:can2?1:.45}}>Weiter →</button></div></div>}
      {step===3&&<div style={panel}><h2 style={{margin:'0 0 15px',fontSize:22}}>So passt der Plan in deine Woche</h2><div style={label}>Wie oft möchtest du pro Woche schwimmen?</div><Chips values={[2,3,4]} value={form.unitsPerWeek} onChange={selectUnits} format={v=>`${v}×`}/><div style={{marginTop:16}}><div style={label}>An welchen Tagen kannst du normalerweise trainieren?</div><div style={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:5}}>{DAYS.map(d=><button key={d} type="button" style={{...chip(form.preferredDays.includes(d)),padding:'9px 0'}} onClick={()=>toggleDay(d)}>{d}</button>)}</div></div>
        {form.goalType!=='event'&&<div style={{marginTop:18}}><div style={label}>Wie viele Wochen möchtest du trainieren?</div><div style={{...small,marginBottom:8}}><strong>Empfehlung: {recommendation} Wochen.</strong> Die Empfehlung berücksichtigt dein aktuelles Schwimmniveau, dein Ziel und die gewünschte Trainingshäufigkeit. Du kannst den Zeitraum trotzdem anpassen.</div><div style={{display:'flex',alignItems:'center',gap:10}}><button style={chip(false)} onClick={()=>{setWeeksManual(true);set('weeksUntilGoal',Math.max(6,form.weeksUntilGoal-1))}}>−</button><strong style={{fontFamily:'sans-serif'}}>{form.weeksUntilGoal} Wochen</strong><button style={chip(false)} onClick={()=>{setWeeksManual(true);set('weeksUntilGoal',Math.min(24,form.weeksUntilGoal+1))}}>+</button></div>{form.weeksUntilGoal<recommendation&&<div style={{...small,marginTop:8,color:'#B06D55'}}>Ambitionierter Zeitrahmen: Der Plan bleibt konservativ und erzwingt keine Belastungssprünge.</div>}</div>}
        {form.goalType==='event'&&<div style={{...small,marginTop:18,padding:10,borderRadius:10,background:'#F2F8F7'}}>📅 Bis zu deinem Event sind es {eventWeeks} Wochen. Die Planlänge richtet sich automatisch danach.</div>}<div style={{marginTop:18,padding:12,borderRadius:13,background:'#F7FAF9',border:'1px solid #DFEBE8',fontFamily:'sans-serif',fontSize:10.5,lineHeight:1.55}}><strong>Dein Plan:</strong> {form.unitsPerWeek}× pro Woche · {form.weeksUntilGoal} Wochen{needsTarget?` · ${Number(effective.targetDistanceM).toLocaleString('de-DE')} m`:''}<br/>Technik, Serien, Pausen und Gesamtmeter werden passend zu deinem aktuellen Stand aufgebaut.</div>{error&&<div style={{marginTop:12,padding:11,borderRadius:10,background:'#FDECEA',color:'#A64E55',fontFamily:'sans-serif',fontSize:11}}>{error}</div>}<div style={{display:'flex',gap:8,marginTop:20}}><button onClick={()=>setStep(2)} style={{...card(false),textAlign:'center'}}>← Zurück</button><button disabled={!can3||loading} onClick={generate} style={{...card(can3),textAlign:'center',opacity:can3&&!loading?1:.5}}>{loading?'Plan wird erstellt…':'Trainingsplan erstellen'}</button></div></div>}
    </main></div>
}
